name: Release / Start a new release

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  start:
    name: Start a new release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read the version.go file
        id: version
        run: .github/workflows/scripts/parse-version.sh

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git fetch origin main

      - name: Create the release branch release-${{ steps.version.outputs.current_without_patch }}
        env:
          BRANCH: release-${{ steps.version.outputs.current_without_patch }}
        run: |
          [[ ! "${GITHUB_REF##*/}" =~ release-v[0-9]+\.[0-9]+\.x ]] && exit 1
