name: Release / Start a new release

on:
  workflow_call:
    inputs:
      hotfix:
        description: Whether the release being started is a hotfix. If not, it is considered a minor version release.
        required: true
        type: boolean
        default: false

  workflow_dispatch:

env:
  RELEASE_KIND: ${{ inputs.hotfix && 'hotfix' || 'release' }}

jobs:
  start:
    name: Create a release pull request against v1
    runs-on: ubuntu-latest
    env:
      PR_TEMPLATE_PATH: .github/PULL_REQUEST_TEMPLATE/$RELEASE_KIND.md
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          echo $RELEASE_KIND
          echo ${{ inputs.hotfix }}
      - uses: actions/checkout@v3

      - name: Read the version.go file
        id: version
        run: _tools/release/parse-version.sh

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git fetch origin main

      - name: Create the release branch release-${{ steps.version.outputs.current }}
        env:
          VERSION: ${{ steps.version.outputs.current }}
        run: |
          git checkout -b release-$VERSION origin/main
          git push -u origin release-$VERSION

      - name: Open the release pull request
        env:
          VERSION: ${{ steps.version.outputs.current }}
        run: |
          gh pr create --title "Release $VERSION" --base v1 --body-file $GITHUB_WORKSPACE/$PR_TEMPLATE_PATH --milestone $VERSION --assignee $GITHUB_ACTOR

      - name: Create the release note draft
        env:
          VERSION: ${{ steps.version.outputs.current }}
        run: |
          gh release create $VERSION --title $VERSION --draft --generate-notes --target v1

      - name: Create the next release GitHub milestone ${{ steps.version.outputs.next_minor }}
        env:
          NEXT_VERSION: ${{ steps.version.outputs.next_minor }}
        run: |
          gh api /repos/$GITHUB_REPOSITORY/milestones \
            --method POST \
            -f title="$NEXT_VERSION" \
            -f state='open' \
            -f description="Tracking milestone for version $NEXT_VERSION"
