name: Merge the release branch

on:
  pull_request:
    types:
      - labeled

jobs:
  merge_and_tag:
    name: Merge the release branch
    if: github.event.label.name == 'ci/release/merge'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get the release version tag
        id: get_version
        run: |
          # Get the version tag out of the release branch name
          [[ "$GITHUB_HEAD_REF" =~ release-v?([[:alnum:]\.\-]+) ]]
          echo "::set-output name=version::${BASH_REMATCH[1]}"

      - name: Configure and fetch the branches
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
          # Fetch the PR, v1 and main branches
          git fetch origin v1 main "$GITHUB_HEAD_REF"

      - name: Merge the PR into the dev branch main
        run: |
          git checkout main
          git merge --no-edit --no-ff "origin/$GITHUB_HEAD_REF"

      - name: Merge the PR into the stable branch v1
        run: |
          git checkout v1
          git merge --no-edit --no-ff "origin/$GITHUB_HEAD_REF"

      - name: Create the git tag v${{ steps.get_version.outputs.version }}
        run: git tag v${{ steps.get_version.outputs.version }}

      - name: Push the branches and tag
        run: |
          # Push the tag, v1, and main
          git push --tags origin v1 main ":$GITHUB_HEAD_REF"

      - name: Remove the workflow label
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr edit ${{ github.event.number }} --remove-label ci/release/merge
