name: Release Workflow

on:
  pull_request:
    types:
      - labeled

jobs:
  run_if_label_matches:
    if: github.event.label.name == 'automerge'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gh --help
      - run: |
          set -ev
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout v1
          git merge --no-ff ${{ github.ref_name }}
          [[ ${{ github.ref_name }} =~ release-v?([[:alnum:]\.\-]+) ]]
          git tag v${BASH_REMATCH[1]}
          git push --tags origin v1
