name: Release Workflow

on:
  pull_request:
    types:
      - labeled

jobs:
  run_if_label_matches:
    if: github.event.label.name == 'automerge'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Remove the workflow label
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit --remove-label automerge
      - name: Merge the release branch
        run: |
          #
          # Merge the PR into the v1 and main branches and tag the resulting v1
          # branch commit with the release version tag
          #
          set -ev
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          # Fetch the v1 and main branches
          git fetch origin v1 main
          # Merge the PR into the main branch
          git checkout main
          git merge --no-edit --no-ff "$GITHUB_REF"
          # Merge the PR into the v1 branch
          git checkout v1
          git merge --no-edit --no-ff "$GITHUB_REF"
          # Get the version tag out of the release branch name and tag the merge
          # result
          [[ ${{ github.ref_name }} =~ release-v?([[:alnum:]\.\-]+) ]]
          git tag v${BASH_REMATCH[1]}
          # Push the tag, v1, and main
          git push --tags origin v1 main
